---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: resume_template.tex
geometry: margin=0.5in

title: "CV"
author: Julianna Rose Calabrese
jobtitle: "Graduate Student in Clinical Psychology"
address: "225 Psychology Building, 1835 Neil Avenue, The Ohio State University, Columbus, OH 43210"
#email: "calabrese.75@osu.edu"
github: jrcalabrese
twitter: jrosecalabrese
#orcid: 0000-0003-1010-2951
#web: jrcalabrese.github.io
updated: TRUE
rdateformat: "`r format(Sys.time(), '%B %d, %Y')`"

fontawesome: yes
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# EDUCATION

**The Ohio State University**, Ph.D. in Clinical Psychology \hfill 2020–Present  
Columbus, OH

**Smith College**, B.A. in Psychology \hfill 2014–2018  
Northampton, MA

# RESEARCH PROJECTS

Schoppe-Sullivan, S. J., Cui, M., & **Calabrese, J. R.** (2024). Advancing Understanding of Overparenting and Child Adjustment: Mechanisms, Methodology, Context, and Development. *Journal of Social and Personal Relationships, 41*(2), 361-371. https://doi.org/10.1177/02654075231213397

Yoon, S., **Calabrese, J. R.**, Yang, J., Logan, J. A. R., Maguire-Jack, K., Min, M. O., Slesnick, N., Browning, C. R., & Hamby, S. (2023). Association between longitudinal patterns of child maltreatment experiences and adolescent substance use. *Child Abuse & Neglect, 147*. https://doi.org/10.1016/j.chiabu.2023.106533 

**Calabrese, J. R.**, & Schoppe-Sullivan, S. J. (2023). Parent emotion regulation and parenting self-efficacy: The moderating role of coparenting. *Journal of Social and Personal Relationships, 40*(12), 3832-3857. https://doi.org/10.1177/02654075231189464

**Calabrese, J. R.**, Goetschius, L. G., Murray, L., Kaplan, M. R., Lopez-Duran, N., Mitchell, C., Hyde, L. W., & Monk, C. S. (2022). Mapping frontostriatal white matter tracts and their association with reward-related ventral striatum activation in adolescence. *Brain Research, 1780*. https://doi.org/10.1016/j.brainres.2022.147803

**Calabrese, J. R.**, Brown, M., & Sacco, D.F. (2016). Casting a Wary Eye: Individuals Higher in Dispositional Distrust Demonstrate More Accurate Discrimination of Trustworthy and Untrustworthy Faces. *Evolutionary Psychological Science, 3*(1), 34–39. https://doi.org/10.1007/s40806-016-0072-6

# CLINICAL SKILLS 

## INTERVENTIONS

* Cognitive-behavioral therapy (CBT)
* Naturalistic developmental behavioral intervention (NDBI)
* RUBI Parent training for disruptive behavior

## ASSESSMENT

* Wechsler Adult Intelligence Scale Fourth Edition (WAIS-IV)
* Minnesota Multiphasic Personality Inventory-2 (MMPI-2)
* Structured Clinical Interview for DSM-5 (SCID-5)
* Early Start Denver Model Curriculum Checklist (ESDM)
* NIH Toolbox Cognitive Battery   

# HONORS & AWARDS

* Ray Travel Award for Service and Scholarship, $1000 (2024)
* Critical Difference for Women Professional Development Grant, The Women's Place, $825 (2023)
* Edward E. Hayes Graduate Research Award, Social and Behavioral Sciences 3rd Place poster presentation, $100 (2022)
* College of Arts and Sciences Division of Social and Behavioral Sciences Scholarship, The Ohio State University (2020) 
* William Sentman Taylor Award, Smith College, $500 (2018)
* Smith College Dean’s List (2015–2016, 2017–2018)

# PROFESSIONAL AFFLIATIONS

* Phi Beta Kappa, Academic Honor Society (May 2018–Present)
* Mu Sigma Rho, the National Honorary Society for Statistics (May 2018–Present)
* Psi Chi, the International Honor Society in Psychology (April 2016–Present)