---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: resume_template.tex
geometry: margin=0.5in

title: "CV"
author: Julianna Rose Calabrese
jobtitle: "Graduate Student in Clinical Psychology"
address: "225 Psychology Building, 1835 Neil Avenue, The Ohio State University, Columbus, OH 43210"
#email: "calabrese.75@osu.edu"
github: jrcalabrese
#twitter: jrosecalabrese
orcid: 0000-0003-1010-2951
web: jrcalabrese.github.io
updated: TRUE
rdateformat: "`r format(Sys.time(), '%B %d, %Y')`"
fontawesome: yes
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# EDUCATION/TRAINING

**Child and Adolescent Behavioral Health**, Doctoral Psychology Internship Program \hfill Expected June 2026    
Canton, OH

* APA-accredited internship at a Community Mental Health Center
* Rotations: Juvenile Justice Program, Sexually Inappropriate Behavior Remediation (SIBR) Program

**The Ohio State University**, Ph.D. in Clinical Psychology \hfill Expected August 2026        
Columbus, OH

* Clinical Psychology Graduate Program (APA and PCSAS Accredited)
* Advisors: Sarah Schoppe-Sullivan, Ph.D., Michael Vasey, Ph.D.
* Dissertation: *Unwrapping the effect of parent emotion socialization on child emotion regulation and social competence*

**The Ohio State University**, M.S. in Psychology \hfill May 2022  
Columbus, OH

* Clinical Psychology Graduate Program (APA and PCSAS Accredited)
* Advisors: Sarah Schoppe-Sullivan, Ph.D., Michael Vasey, Ph.D.
* Thesis: *Parent emotion regulation, parenting self-efficacy, and child emotion regulation: The moderating role of coparenting*

**Smith College**, B.A. in Psychology \hfill May 2018  
Northampton, MA

* Graduated cum laude, highest honors in Psychology
* Minor in Applied Statistics
* Advisor: Nnamdi Pole, Ph.D.
* Thesis: *Don't take it at face value: A case study on facial expressivity, emotional coherence, and posttraumatic stress disorder*

# CLINICAL SKILLS 

## INTERVENTIONS

* Cognitive-behavioral therapy (CBT)
* Trauma-focused cognitive behavioral therapy (TF-CBT)
* Naturalistic developmental behavioral intervention (NDBI)
* Parent-child interaction therapy (PCIT)
* RUBI Parent training for disruptive behavior
* Social-emotional learning (SEL)
* Evidence-based treatment for problem sexual behaviors and sexually inappropriate behaviors in children and adolescents (Pathways Fifth Edition)

## ASSESSMENT

* Wechsler Adult Intelligence Scale, Fourth Edition (WAIS-IV)
* Wechsler Intelligence Scale for Children, Fifth Edition (WISC-V)
* Wechsler Individual Achievement Test, Fourth Edition (WIAT-IV)
* Minnesota Multiphasic Personality Inventory-2 (MMPI-2)
* Structured Clinical Interview for DSM-5 (SCID-5)
* Early Start Denver Model Curriculum Checklist (ESDM)
* NIH Toolbox Cognitive Battery   

# HONORS & AWARDS

* Division 43 Convention Travel Award, $400 (2025)
* Ray Travel Award for Service and Scholarship, $1000 (2024)
* Critical Difference for Women Professional Development Grant, The Women's Place, $825 (2023)
* College of Arts and Sciences Division of Social and Behavioral Sciences Scholarship, The Ohio State University (2020) 
* William Sentman Taylor Award, Smith College, $500 (2018)
* Smith College Dean’s List (2015–2016, 2017–2018)